### PR TITLE
Support for auxiliary object classes and OP_RETURN_DEFAULT_ATTRIBUTES

### PR DESCRIPTION
**Pull request by semancik**
See mailing list ...

### CODE REVIEW

**Comment by ilgrosso** [comment]
Thanks for this PR; could you please squash commits into one?
Is there any issue on JIRA for this work?

**Comment by semancik** [comment]
Do you really want to squash the commits? E.g. there are two somehow independent features. So it will make sense to be at least two commits. But the commits are somehow interleaved ... and squashing them is additional work. And as this fork is a public repository I really should not rewrite its history and it will get merging back real pain and so on ... simply speaking, I do not thing it is worth the effort (read: I'm too lazy to do it).
But I will create Jiras, though.

**Comment by ilgrosso** [comment]
Thanks for creating [BASE-49](https://connid.atlassian.net/browse/BASE-49).

If you don't want to squash your commits, someone else will have to do it: there are merge commits in this PR and also commits from other PRs, which definitely not nice to read in the commit history.

Moreover, there is need to reference BASE-49 in the squashed commit message.

**Comment by semancik** [comment]
OK, OK. I'll do it. But now I understand that "community over code" is just a different word for bureaucracy :-) ... I'm joking ... but anyway. I can cope. But this approach may discourage other contributors. The question is whether we want to have a pretty source code history or we want a working code ...

**Comment by ilgrosso** [comment]
Working code also means maintenance, in the future, possibly by others.

If possible, for further contributions - which are more than welcome, naturally - it might be the case to create feature branches, named after a JIRA issue, on your own fork.

So, for example:

1. create JIRA-XX for feature A or bug B
2. create branch JIRA-XX on your own fork
3. rebase JIRA-XX on ConnId's master (not your own master)
4. commit -> commit -> commit
5. create PR
6. review -> squash and reword commit message including "JIRA-XX" if necessary
7. merge

This is quite common practice (excluding GIT bits, for SVN-based projects) in all projects I've been involved in, either at The ASF or not.

**Comment by semancik** [comment]
OK. Done.

**Pull request merged**
