### PR TITLE
[BASE-59] Delta-based update operation

### PR DESCRIPTION
**Pull request by semancik**

### CODE REVIEW

**Comment by ilgrosso** [comment]
Thanks for this PR @semancik - shall we resolve [BASE-59](https://connid.atlassian.net/browse/BASE-59) and proceed with 1.4.3.0 release, then?

**Comment by semancik** [comment]
Thanks for merging. We can resolve BASE-59. But please wait a little while with the release. We are now entering a period of quite an intense testing during next few weeks. So if there are any bugs left in the framework they are likely to be discovered and fixed. So I guess it would be better to make a release after the testing (approx. mid-June).

**Comment by ilgrosso** [comment]
Agree, please resolve BASE-59 then.
I'll be waiting for your green light before proceeding with 1.4.3.0.

**Comment by semancik** [comment]
Also, thanks for fixing the coverity issues. I have tried to get the details what's wrong, but it was not included in the mail from coverity and I could not find it on the page linked from the mail either. Is there some trick how to get the details?

**Comment by ilgrosso** [comment]
I guess you'll need to add yourself to the project there: https://scan.coverity.com/memberships/new?project_id=tirasa-connid

**Pull request merged**
