### PR TITLE
Implementation of BASE-83 and BASE-85

### PR DESCRIPTION
**Pull request by semancik**
Connector configuration discovery and Enumerated possible values for configuration properties

### CODE REVIEW

**Comment by ilgrosso** [comment]
Thanks @semancik 
Any chance you can add some test cases for the new features introduced?

**Comment by semancik** [comment]
Thought about tests, but I have not found any appropriate place. I guess it would require a "dummy" connector with the configuration discovery feature. Do you know of an appropriate place where to place the test and how to structure it? Or maybe even a similar test that I can use as inspiration? That would be very appreciated.

For now, I have created tests for our LDAP connector, testing it with embedded OpenDJ. Therefore the feature is tested indirectly. Yet, I fully understand that having a test in the framework suite would be much better.

**Comment by ilgrosso** [comment]
@semancik since we're adding a new Op (`DiscoveryConfigurationOp`), I think you could proceed as for other Ops' tests in https://github.com/Tirasa/ConnId/tree/master/java/connector-framework-contract/src/main/java/org/identityconnectors/contract/test

**Comment by semancik** [comment]
@ilgrosso I have added contract tests, as suggested. However, I have to admit I have no idea what I'm doing. Is there any info about the contract tests? How they are used, how to actually test them, etc?
As far as I have seen, those are not direct tests for the framework, but rather a tests that can be used by a connector to test contract compliance. However, I was not able to figure much more. Any hints?

**Comment by ilgrosso** [comment]
@semancik mmm I actually don't know much about contract tests - AFAICT in fact, your new test class is not invoked during the build (as it happens to the other test classes I've pointed out above).

Anyway, better having the test class you've added than nothing.

Thanks for your contribution, I am going to merge.

**Pull request merged**
