### PR TITLE
BASE 46: Support for Date/Time data type

### PR DESCRIPTION
**Pull request by semancik**

### CODE REVIEW

**Comment by ilgrosso** [comment]
Thanks @semancik - shall we resolve https://connid.atlassian.net/browse/BASE-46?

**Comment by semancik** [comment]
I just did. I'm always confused when it is the right time to resolve the issue .. whether it is when I'm finished (PR submission), when PR is merged or when the code is released.

**Comment by ilgrosso** [comment]
I think the workflow is quite common:
1. PR merged and work completed => issue resolved
2. release time => issue closed

**Comment by ilgrosso** [comment]
I have manually linked this PR to JIRA, as the commit was erroneously referencing "BASE 46" and not "BASE-46"

**Pull request merged**
